### PR TITLE
Wrong Xml path for externalOutput

### PR DESCRIPTION
**Pull request by peterbaumert**

### CODE REVIEW

**Comment by peterbaumert** [comment]
hey @jensstigaard could you have a look and potentially merge this?

**Comment by jensstigaard** [comment]
Thanks for your pull request. I am sorry the code were wrong in the first place - thanks for catching the error. I am now merging and patching the npm package.

**Comment by jensstigaard** [comment]
Released npm package vmix-js-utils @ v 4.0.19 where this fix is included.

**Comment by peterbaumert** [comment]
Great thank you. No need be sorry, im happy for your project in the first place.

**Pull request merged**
